swagger: "2.0"
info:
  description: |
    This is the definition of REST API for fizzbuzz
  version: "1.0.0"
  title: fizzbuzz REST API
host: localhost:3001
schemes:
  - http
paths:
  /{count}:
    get:
      tags:
        - fizzbuzz
      summary: Gets the array of numbers upto count(number passed in the request) with the below conditions.
      description: Gets the array of numbers upto count(number passed in the request) with the below conditions.
      operationId: getfizzbuzz
      produces:
        - application/json
        - application/xml
      parameters:           
        - in: path
          name: count
          description: Count of numbers till where fizzbuzz algorithm will be implemented
          required: true
          type: integer
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Response"        
        "400":
          description: Invalid Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:    
  ErrorResponse:
    type: object
    properties:
      statusCode:
        type: integer
        format: int64
      message:
        type: string
  Response:
    type: object
    properties:
      statusCode:
        type: integer
        format: int64
      data:
        type: array
        items:
          type: object